name: main

on: 
  push:
    branches:
      - main
      
jobs:
  blog_app_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Hi
        run: |
          echo "hello world"
      - name: Date
        run: Date
      - name: Dir
        run: ls -l
